version: '3'

services:
  nodeapp:
    build: 
      context: ./node
      dockerfile: Dockerfile.prod
    image: dlcurado/fullcycle-docker-nodeapp:latest
    container_name: nodeapp
    tty: true
    entrypoint: wait-for mysqldb:3306 -t 40 -- ./start.sh
    volumes:
      - ./node:/usr/src/app
    networks:
      - nginxnodenet
    depends_on:
      - mysqldb
  
  nginxapp:
    build: 
          context: ./nginx
          dockerfile: Dockerfile.prod
    image: dlcurado/fullcycle-docker-nginx:latest
    container_name: nginxapp
    networks:
      - nginxnodenet
    ports:
      - "8080:80"
    depends_on:
      - nodeapp
  
  mysqldb:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: mysqldb
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./mysql_scripts/people.sql:/docker-entrypoint-initdb.d/people.sql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - nginxnodenet

networks:
  nginxnodenet:
    driver: bridge