#FROM nginx:1.25.2-alpine
FROM nginx:latest

RUN apt-get update


RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d

COPY html/ /usr/share/nginx/html

CMD ["nginx","-g", "daemon off;"]

#USER nginx