#FROM nginx:1.25.2-alpine
FROM nginx:latest

RUN apt-get update

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d

COPY html/ /usr/share/nginx/html
#RUN mkdir /var/www/public -p && touch /var/www/public/index.js
#RUN mkdir /usr/src/app -p && touch /usr/src/app/index.js

#ENTRYPOINT ["/docker-entrypoint.sh"]

CMD ["nginx", "-g", "daemon off;"]