FROM node

RUN apt-get update

WORKDIR /usr/src/app

RUN npm install express
RUN npm install dotenv
RUN npm install mysql2
RUN nom install node-random-name

COPY . .

EXPOSE 3000

CMD [ "node", "index.js" ]